function cases = mcrtcases()
   % Seeded parameter sets shared by the smoke, determinism, energy, and
   % golden tests. Fields: name, ka, ks, g, Z, dz (same units as mcrt), N,
   % and the seed for rng(seed,'twister'). vdh_reflectance is the van de
   % Hulst tau=2 slab from mcrt_verify.m (albedo 0.9). absorbing has albedo
   % 0.1 so most weight is absorbed. mini_fluence has albedo 0.99 and a
   % thin slab. It exercises the fluence tallies at a fraction of the cost
   % of the albedo-0.999 verification case, which never runs here.
   cases = struct( ...
      'name', {'vdh_reflectance', 'absorbing', 'mini_fluence'}, ...
      'ka', {10, 90, 1}, ...
      'ks', {90, 10, 99}, ...
      'g', {0.75, 0.5, 0.9}, ...
      'Z', {0.02, 0.05, 0.1}, ...
      'dz', {0.001, 0.005, 0.005}, ...
      'N', {1e4, 1e4, 2e3}, ...
      'seed', {42, 43, 44});
end
