function cases = mcrtcases()
   % Seeded parameter sets shared by the smoke, determinism, and energy tests.
   % Fields: name, ka, ks, g, Z, dz (same units as mcrt), and the seed for
   % rng(seed,'twister'). The vdh case is the van de Hulst tau=2 slab from
   % mcrt_verify.m; the absorbing case has w = 0.5 so most weight is absorbed.
   cases = struct( ...
      'name', {'vdh_reflectance', 'absorbing'}, ...
      'ka', {10, 50}, ...
      'ks', {90, 50}, ...
      'g', {0.75, 0.5}, ...
      'Z', {0.02, 0.05}, ...
      'dz', {0.001, 0.005}, ...
      'seed', {42, 43});
end
