function [names, values, notes] = impactquantities(RT)
   % Scalar quantities that summarize one mcrt result for the impact and
   % retrospective tables. Radial spread uses the packet weights per
   % radial bin, which are the per-area tallies times the areas the kernel
   % divided by, so kernels with and without RT.grid.dA compare alike.
   % r50 is the radius that encloses half the diffuse weight inside R.
   % With no argument only names and notes are returned, so callers can
   % size their tables without a run.
   names = {'Rdf'; 'Tdf'; 'Tdr'; 'Rdr'; 'Adf'; 'Rdf_a(1)'; 'Tdf_a(1)'; ...
      'Rdf_r(1)'; 'Tdf_r(1)'; 'r50 R'; 'r50 T'; 'phi_rz(1,1)'; 'phi_z(1)'};
   notes = { ...
      'hemispherical diffuse reflectance, a sum of packet weights'; ...
      'hemispherical diffuse transmittance, a sum of packet weights'; ...
      'direct transmittance; A moves scattered grazing exits out of it'; ...
      'direct reflectance; zero for the vertical source after A'; ...
      'total diffuse absorbed fraction, a sum of packet weights'; ...
      'first angular bin per steradian; S corrects its solid angle'; ...
      'first angular bin per steradian; S corrects its solid angle'; ...
      'first radial bin per area; B moves packets, S corrects the area'; ...
      'first radial bin per area; B moves packets, S corrects the area'; ...
      'radius enclosing half the reflected diffuse weight; B'; ...
      'radius enclosing half the transmitted diffuse weight; B'; ...
      'on-axis surface fluence density; C confines the pencil, S sets dV'; ...
      'surface plane-integrated fluence; unchanged by every fix'};
   if nargin == 0
      values = [];
      return
   end
   if isfield(RT.grid, 'dA')
      area = RT.grid.dA;
   else
      area = 2*pi*RT.grid.ri.*RT.grid.dr;
   end
   values = [RT.Rdf; RT.Tdf; RT.Tdr; RT.Rdr; RT.Adf; RT.Rdf_a(1); ...
      RT.Tdf_a(1); RT.Rdf_r(1); RT.Tdf_r(1); ...
      r50(RT.Rdf_r, area, RT.grid.ri); r50(RT.Tdf_r, area, RT.grid.ri); ...
      RT.phi_rz(1, 1); RT.phi_z(1)];
end

function r = r50(perarea, area, ri)
   % Radius of the first bin whose cumulative weight reaches half the
   % weight inside R (the overflow bin is excluded). With no diffuse
   % weight inside R there is no such radius, and r is NaN.
   w = perarea(1:end-1).*area(1:end-1);
   c = cumsum(w);
   if c(end) <= 0
      r = NaN;
      return
   end
   k = find(c >= 0.5*c(end), 1);
   r = ri(k);
end
